#! /bin/sh

autorandr --change

## Launch Polybar
bash ~/.config/polybar/launch.sh --shades

emote &
dunst &
feh --bg-fill ~/Pictures/wp5204110.jpg 
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends --unredir-if-possible &
lxpolkit &
gpaste-client start

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         2
bspc config window_gap          20
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop='^8'
bspc rule -a obs desktop='^7'
